---
- hosts: local
  tasks:
  - name: "Checkout dotfiles"
    git: repo=ssh://git@github.com/makkus/dotfiles 
         dest=~/dotfiles
         accept_hostkey=True
         executable=~/.nix-profile/bin/git
  - name: "Unlock encrypted dotfiles"
    shell: . ~/.nix-profile/etc/profile.d/nix.sh && ~/.nix-profile/bin/git-crypt unlock
           chdir=~/dotfiles

- hosts: local
  tasks:
  - name: "Install spacemacs"
    git: repo=git://github.com/syl20bnr/spacemacs
         dest=~/.emacs.d
         executable=~/.nix-profile/bin/git
  - name: "Install zplug"
    git: repo=git://github.com/b4b4r07/zplug
         dest=~/.zplug
         executable=~/.nix-profile/bin/git
  

- hosts: local
  vars:
    base_packages:
      - bash
      - beets
      - flake8
      - git
      - nix
      - percol
      - spacemacs
      - systemd
      - zile
      - zsh
    x_packages:
      - dunst
      - fonts
      - i3
      - redshift
      - rofi-pass
      - Xresources
  tasks:
  - name: "Remove potential setup configs"
    shell: rm -rf ~/.bash_profile ~/.bashrc ~/.profile ~/.nix-pkgs
  - name: "Create config symlinks with stow"
    shell: . ~/.nix-profile/etc/profile.d/nix.sh && stow {{ item }}
           chdir=~/dotfiles
    with_items:
      - "{{ base_packages + x_packages }}"
