---
- hosts: local
  tasks:
    - name: "Copy custom Xsession file for LightDM"
      become: yes
      become_user: root
      become_method: sudo
      copy: src=data/Markus.desktop dest=/usr/share/xsessions/Markus.desktop mode=755
    - name: "Get username"
      shell: whoami
      register: username
    - name: "Add zsh to shells"
      become: yes
      become_user: root
      become_method: sudo
      lineinfile: dest=/etc/shells line="/home/{{ username.stdout }}/.nix-profile/bin/zsh"
    - name: "Set default shell to zsh"
      become: yes
      shell: usermod -s "/home/{{ username.stdout }}/.nix-profile/bin/zsh" {{ username.stdout }}
