---
- hosts: local
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  tasks:
  - name: install python dependencies
    apt: pkg={{item}} state=installed
    with_items:
          - python-setuptools
          - python3-setuptools
          - python-dev
          - python3-dev
          - virtualenvwrapper
  - name: install pip
    command: easy_install pip creates=/usr/local/bin/pip
  - name: install pip3
    command: easy_install3 pip creates=/usr/local/bin/pip3

- hosts: local
  vars:
    pip_packages:
      - ansible
      - autoenv
      - beets
      - cookiecutter
      - discogs-client
      - docker-compose
      - percol
      - pip
      - pyacoustid
      - pylast
      - thefuck
      - virtualenv
      - virtualenv-clone
      - virtualenvwrapper
    pip3_packages:
      - i3barfodder
  tasks:
  - name: install pip packages
    become: yes
    become_user: root
    become_method: sudo
    pip: name={{ item }} state=latest
         executable=pip2
    with_items:
      - "{{ pip_packages }}"
  - name: install pip3 packages
    become: yes
    become_user: root
    become_method: sudo
    pip: name={{ item }} state=latest
         executable=pip3
    with_items:
      - "{{ pip3_packages }}"
